name: OzCHI 2022
tagline: "OzCHI 2022: connected creativity"
date: 28 Nov - 2 Dec, 2022
citation_date: Nov 2022
proceedings_title: Proceedings of the 34th Australian Conference on Human-Computer Interaction (HCI)
analytics: UA-
logo:
  image: static/images/ozchi-logo-text-black.png
  width: 180px
  height: auto
biglogo:
  image: static/images/ozchi-logo-white.png
  width: 500px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: OzCHI
page_title:
  prefix: 'OzCHI 2022'
  separator: ': '
background_image: static/images/kambri.jpg
organization: OzCHI and HFESA

# Remove or change to your chat server.
chat_server: miniconf.sloppy.zone
default_presentation_id: 38922815
default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
